<?php

namespace Sentric\iSecureBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FunctionalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FunctionalAreaRepository extends EntityRepository
{
}
